#!/usr/bin/env python3

from __future__ import annotations

import argparse
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from PIL import Image, ImageDraw


APP_NAME = "Telegram"
DEFAULT_CHAT_NAME = "DocMolder"
DEFAULT_ASSET_DIR = Path("tmp/manual-test-assets")
SUPPORTED_PLANS = ("full", "wizard-a4", "pdf-followup", "history", "public-trust")


@dataclass(frozen=True)
class Step:
    kind: str
    value: str
    delay_seconds: float = 0.8


def build_assets(asset_dir: Path) -> dict[str, Path]:
    asset_dir.mkdir(parents=True, exist_ok=True)

    image_paths: list[Path] = []
    colors = [(230, 240, 255), (255, 240, 230)]
    for index, color in enumerate(colors, start=1):
        path = asset_dir / f"smoke_image_{index}.jpg"
        image = Image.new("RGB", (1200, 1600), color)
        draw = ImageDraw.Draw(image)
        draw.rectangle((80, 80, 1120, 1520), outline=(40, 60, 90), width=8)
        draw.text((140, 160), f"DocMolder smoke image {index}", fill=(20, 20, 20))
        draw.text((140, 240), "Generated by smoke_telegram_desktop.py", fill=(20, 20, 20))
        image.save(path, quality=92)
        image_paths.append(path)

    pdf_path = asset_dir / "smoke_source.pdf"
    pdf_image = Image.new("RGB", (1240, 1754), "white")
    pdf_draw = ImageDraw.Draw(pdf_image)
    pdf_draw.text((120, 140), "DocMolder smoke PDF page 1", fill="black")
    pdf_draw.text((120, 240), "Compression / grayscale / follow-up", fill="black")
    pdf_image.save(pdf_path, "PDF", resolution=150.0)

    return {
        "image_1": image_paths[0],
        "image_2": image_paths[1],
        "pdf": pdf_path,
    }


def build_plan(plan_name: str, assets: dict[str, Path]) -> list[Step]:
    plans = {
        "wizard-a4": [
            Step("text", "/reset", 1.0),
            Step("file", str(assets["image_1"]), 1.2),
            Step("file", str(assets["image_2"]), 1.5),
            Step("text", "PDF da immagini", 1.0),
            Step("text", "Si, impagina in A4", 1.0),
            Step("text", "bordi stretti", 1.0),
        ],
        "pdf-followup": [
            Step("text", "/reset", 1.0),
            Step("file", str(assets["pdf"]), 1.2),
            Step("text", "Comprimi PDF", 1.0),
            Step("wait", "4.0", 4.0),
            Step("text", "Scala di grigi", 1.0),
        ],
        "history": [
            Step("text", "/history", 1.0),
        ],
        "public-trust": [
            Step("text", "/reset", 1.0),
            Step("text", "/start", 1.0),
            Step("text", "/help", 1.0),
            Step("text", "/start privacy", 1.0),
            Step("text", "/status", 1.0),
            Step("file", str(assets["pdf"]), 1.2),
            Step("text", "Comprimi PDF", 1.0),
            Step("wait", "4.0", 4.0),
            Step("text", "/history", 1.0),
            Step("text", "/reset", 1.0),
        ],
    }
    if plan_name == "full":
        return [
            *plans["wizard-a4"],
            Step("wait", "4.0", 4.0),
            Step("text", "Scala di grigi", 1.0),
            *plans["history"],
        ]
    if plan_name not in plans:
        raise ValueError(f"Piano smoke non supportato: {plan_name}")
    return plans[plan_name]


def run_osascript(script: str) -> None:
    subprocess.run(["osascript", "-e", script], check=True)


def activate_telegram() -> None:
    run_osascript(f'tell application "{APP_NAME}" to activate')
    time.sleep(0.6)


def open_chat(chat_name: str) -> None:
    script = f'''
tell application "{APP_NAME}" to activate
tell application "System Events"
    keystroke "k" using command down
    delay 0.4
    keystroke "{escape_applescript(chat_name)}"
    delay 0.4
    key code 125
    delay 0.2
    key code 36
end tell
'''
    run_osascript(script)
    time.sleep(1.0)


def send_text(text: str) -> None:
    script = f'''
tell application "{APP_NAME}" to activate
tell application "System Events"
    keystroke "{escape_applescript(text)}"
    delay 0.2
    key code 76
end tell
'''
    run_osascript(script)


def send_file(path: Path) -> None:
    resolved = path.resolve()
    script = f'''
set the clipboard to (POSIX file "{escape_applescript(str(resolved))}")
tell application "{APP_NAME}" to activate
tell application "System Events"
    keystroke "v" using command down
    delay 0.5
    key code 36
end tell
'''
    run_osascript(script)


def escape_applescript(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def print_plan(chat_name: str, plan_name: str, steps: list[Step]) -> None:
    print(f"Chat: {chat_name}")
    print(f"Piano: {plan_name}")
    for index, step in enumerate(steps, start=1):
        print(f"{index}. {step.kind}: {step.value}")


def list_plans() -> None:
    print("Piani disponibili:")
    for plan_name in SUPPORTED_PLANS:
        print(f"- {plan_name}")


def cleanup_assets(asset_dir: Path) -> None:
    if not asset_dir.exists():
        return
    for path in asset_dir.iterdir():
        if path.is_file():
            path.unlink()


def execute_plan(
    chat_name: str,
    plan_name: str,
    steps: list[Step],
    *,
    dry_run: bool,
    pause_between_steps: bool,
) -> None:
    print_plan(chat_name, plan_name, steps)
    if dry_run:
        return

    activate_telegram()
    open_chat(chat_name)

    for index, step in enumerate(steps, start=1):
        print(f"[{index}/{len(steps)}] {step.kind}: {step.value}")
        if step.kind == "text":
            send_text(step.value)
        elif step.kind == "file":
            send_file(Path(step.value))
        elif step.kind == "wait":
            pass
        else:
            raise ValueError(f"Tipo step non supportato: {step.kind}")
        if pause_between_steps:
            input("Invio per continuare con il prossimo step...")
        time.sleep(step.delay_seconds)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Automazione rapida degli smoke test su Telegram Desktop per DocMolder."
    )
    parser.add_argument(
        "--chat",
        default=DEFAULT_CHAT_NAME,
        help=f"Nome chat Telegram da aprire. Default: {DEFAULT_CHAT_NAME}",
    )
    parser.add_argument(
        "--plan",
        default="full",
        choices=SUPPORTED_PLANS,
        help="Piano smoke da eseguire.",
    )
    parser.add_argument(
        "--asset-dir",
        default=str(DEFAULT_ASSET_DIR),
        help=f"Cartella locale per gli asset temporanei. Default: {DEFAULT_ASSET_DIR}",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Stampa il piano e prepara gli asset senza inviare nulla a Telegram.",
    )
    parser.add_argument(
        "--pause",
        action="store_true",
        help="Chiede conferma tra uno step e il successivo.",
    )
    parser.add_argument(
        "--cleanup-assets",
        action="store_true",
        help="Rimuove gli asset generati a fine esecuzione.",
    )
    parser.add_argument(
        "--list-plans",
        action="store_true",
        help="Mostra i piani disponibili ed esce.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    if args.list_plans:
        list_plans()
        return 0

    asset_dir = Path(args.asset_dir)
    assets = build_assets(asset_dir)
    steps = build_plan(args.plan, assets)
    execute_plan(
        args.chat,
        args.plan,
        steps,
        dry_run=args.dry_run,
        pause_between_steps=args.pause,
    )
    if args.cleanup_assets:
        cleanup_assets(asset_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
